apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ix3te1t0a-python
  janus-idp.io/tekton: ix3te1t0a-python
  backstage.io/kubernetes-id: ix3te1t0a-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ix3te1t0a-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
